
services:
  frontend:
    build: ./webapp
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
