---
- name: Rejoindre le domaine Active Directory
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ ad_admin_user }}"
    domain_admin_password: "{{ ad_admin_password }}"
    hostname: "{{ ansible_hostname }}"
    state: domain
  register: domain_join

- name: Redémarrer si nécessaire après la jonction au domaine
  win_reboot:
  when: domain_join.reboot_required
