---
- name: Mise 0 jour des paquets
  pacman:
    update_cache: yes

- name: Installation du package bind
  pacman:
    name: bind
    state: present

- name: Demarrage et activation du fichier bind9
  systemd:
    name: named
    state: started
    enabled: yes

- name: Copier le fichier de configuration named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0644
  notify: Redémarrer BIND

- name: Copie du fichier de zone directe
  template:
    src: db.direct.j2
    dest: /var/named/direct.zone
    owner: root
    group: named
    mode: 0644
  notify: Redémarrer BIND

- name: Copie du fichier de zone inverse
  template:
    src: db.indirect.j2
    dest: /var/named/inverse.zone
    owner: root
    group: named
    mode: 0644
  notify: Redémarrer BIND

- name: Copie du fichier resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  become: yes
